sudo: required
services:
  - docker

before_install:
  - docker build -t allenwalker31/docker_learning:latest -f Dockerfile.dev .

scripts:
  - docker run allenwalker31/docker_learning:latest npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "name of S3 bucket"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secrete_access_key: "$AWS_SECRETE_KEY"